development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pizza_biz_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pizza_biz_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock